In [17]:
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split

iris=datasets.load_iris()

x=iris.data
y=iris.target

x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [18]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(x)

print(scaler.mean_)

x=scaler.transform(x)

x[:5]

[5.84333333 3.05733333 3.758      1.19933333]


array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [19]:
x_train , x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,shuffle=True)

In [20]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC


clf=OneVsOneClassifier(LinearSVC())

In [26]:
#train

model= clf.fit(x_train,y_train)

In [27]:
#USING THE MODEL/PREDICTOR TO PREDICT 

y_pred=model.predict(x_test)

In [28]:
#viewing the Accuracy

print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.96


In [29]:
import numpy as np

from sklearn.model_selection import cross_val_score


cross_val_result=cross_val_score(clf,x,y,cv=4)

print("Cross validation scores",cross_val_result)
print("Avarage accurcy ",np.mean(cross_val_result))

Cross validation scores [1.         0.97368421 0.94594595 1.        ]
Avarage accurcy  0.9799075391180655
